In [1]:
import numpy as np

In [2]:
shape = (3, 256, 256)
a1 = np.ones(shape)
a2 = 2*a1
a3 = 3*a1

In [4]:
a = np.stack((a1, a2, a3), axis=0)
print(a)
print(a.shape)

[[[[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]]

  [[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]]

  [[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]]]


 [[[2. 2. 2. ... 2. 2. 2.]
   [2. 2. 2. ... 2. 2. 2.]
   [2. 2. 2. ... 2. 2. 2.]
   ...
   [2. 2. 2. ... 2. 2. 2.]
   [2. 2. 2. ... 2. 2. 2.]
   [2. 2. 2. ... 2. 2. 2.]]

  [[2. 2. 2. ... 2. 2. 2.]
   [2. 2. 2. ... 2. 2. 2.]
   [2. 2. 2. ... 2. 2. 2.]
   ...
   [2. 2. 2. ... 2. 2. 2.]
   [2. 2. 2. ... 2. 2. 2.]
   [2. 2. 2. ... 2. 2. 2.]]

  [[2. 2. 2. ... 2. 2. 2.]
   [2. 2. 2. ... 2. 2. 2.]
   [2. 2. 2. ... 2. 2. 2.]
   ...
   [2. 2. 2. ... 2. 2. 2.]
   [2. 2. 2. ... 2. 2. 2.]
 

In [5]:
unique, counts = np.unique(a, return_counts=True)
counts_dict = dict(zip(unique, counts))
print(f'Class pixels of final mask: {counts_dict}')

Class pixels of final mask: {1.0: 196608, 2.0: 196608, 3.0: 196608}


In [6]:
c = counts_dict

In [7]:
print(c)

{1.0: 196608, 2.0: 196608, 3.0: 196608}


In [8]:
res = c + counts_dict

TypeError: unsupported operand type(s) for +: 'dict' and 'dict'

In [11]:
print(c.values())
print(c.keys())

dict_values([196608, 196608, 196608])
dict_keys([1.0, 2.0, 3.0])


In [12]:
print(unique)

[1. 2. 3.]
